# Generated by Django 4.0.5 on 2022-06-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlgenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('workclass', models.CharField(blank=True, max_length=255, null=True)),
                ('fnlwgt', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('educationalnum', models.IntegerField(blank=True, null=True)),
                ('maritalstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('race', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('capitalgain', models.IntegerField(blank=True, null=True)),
                ('capitalloss', models.IntegerField(blank=True, null=True)),
                ('hoursperweek', models.IntegerField(blank=True, null=True)),
                ('nativecountry', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'adult',
                'managed': False,
            },
        ),
    ]
