# Generated by Django 4.0.5 on 2022-07-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqlgenerator', '0005_alter_trainingdata_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdata',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sqlgenerator.query'),
        ),
    ]
