# Generated by Django 4.0.5 on 2022-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_rename_modeltype_trainedmodel_modeldescr'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='modelType',
            field=models.CharField(default='Test/no real model', max_length=255),
            preserve_default=False,
        ),
    ]
