# Generated by Django 4.0.5 on 2022-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_alter_trainedmodel_modeltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='f1score',
            field=models.FloatField(null=True),
        ),
    ]
