# Generated by Django 4.0.5 on 2022-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_trainedmodel_f1score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainedmodel',
            old_name='f1score',
            new_name='f1scoreTest',
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='f1scoreVal',
            field=models.FloatField(null=True),
        ),
    ]
