# Generated by Django 4.0.5 on 2022-07-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_alter_trainedmodel_modeltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='modelParams',
            field=models.JSONField(null=True),
        ),
    ]
