# Generated by Django 4.0.5 on 2022-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_trainedmodel_modelparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='maxEvals',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
