# Generated by Django 4.0.5 on 2022-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_trainedmodel_removelowestcertaintypercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainedmodel',
            name='modelType',
            field=models.CharField(choices=[('gdbss', 'Gradient Boosting Semi-Supervised'), ('gdbr', 'Gradient Boosting Regression'), ('gdbs', 'Gradient Boosting Supervised'), ('dt', 'Decision Tree Supervised'), ('dtss', 'Decision Tree Semi-Supervised')], max_length=255),
        ),
    ]
